---
title: "Deconvolution using MuSiC"
date: "`r format(Sys.time(), '%B %d, %Y')`"
params:
  inSCE: inSCE
  analysisName: analysisName
  analysisType: analysisType
  heatmapTitle: heatmapTitle
output:
  html_document:
    number_sections: yes
    toc: yes
    code_folding: hide
---



```{r MuSiC_library, message = FALSE, include = FALSE}
require(singleCellTK)
require(ggplot2)
require(dplyr)
require(SingleCellExperiment)
require(S4Vectors)
```



```{r MuSiC_params}
inSCE <- params$inSCE
analysisName<-params$analysisName
analysisType<-params$analysisType
heatmapTitle<-params$heatmapTitle
```



```{r MuSiC_output, results = "asis", fig.align = "center"}

results <- plotMusicResults(inSCE = inSCE, analysisType = analysisType, analysisName =analysisName, heatmapTitle = heatmapTitle)


  # Tab for tool results
  cat(paste0('# Music Results', ' {.tabset} \n\n'))

  # Subtab for a separate plot of the tool results
  cat(paste0('## Heatmap \n\n'))
  if (analysisType %in% c("EstCellProp","PreGroupedClustProp")){
  metadata(results)$sctk$music[[analysisName]][["Heatmap"]]
  }
  
  if(analysisType == "SingleCellClust"){
  
  cat(paste0('## Clusters \n\n'))
  metadata(results)$sctk$music[[analysisName]][["clusters"]]
 #  getMusicPlots(sce,analysisName,"Clusters")
  }
  
  # Final tab to display the parameters used
  cat(paste0('## Parameters \n\n'))
  print(params)
```



```{r MuSiC_description, include = FALSE, warning = FALSE, message = FALSE}
description_toolName <- descMusic()

# {.unlisted .unnumbered .toc-ignore}
`r description_runMusic`
```





